// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi1yHSbgY7TwWKGhw9YVLbJK-5Fzu0I_A',
    appId: '1:926253572011:web:56efa6aaa3900302687cee',
    messagingSenderId: '926253572011',
    projectId: 'car-charger-app-e54ec',
    authDomain: 'car-charger-app-e54ec.firebaseapp.com',
    storageBucket: 'car-charger-app-e54ec.appspot.com',
    measurementId: 'G-1RNGS6YFTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3-BVlwfGkUdeUJR_Ivi2G63jBgCEMYz4',
    appId: '1:926253572011:android:f048ea85ed2de9ff687cee',
    messagingSenderId: '926253572011',
    projectId: 'car-charger-app-e54ec',
    storageBucket: 'car-charger-app-e54ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArr7WmnXl-JDxPV9IZcq5ycDqOcfjJSSk',
    appId: '1:926253572011:ios:6727a88ff62d4247687cee',
    messagingSenderId: '926253572011',
    projectId: 'car-charger-app-e54ec',
    storageBucket: 'car-charger-app-e54ec.appspot.com',
    iosClientId: '926253572011-vbte0rvbur2beb82knjbn1auhvjk3ulu.apps.googleusercontent.com',
    iosBundleId: 'com.example.envorsoChargin',
  );
}
